### ISSUE TITLE
Incremental builds don't work when modifying sub-root imports

### ISSUE THREAD

**Issue by christianvuerings** [amireh/happypack#123] opened 2017-01-21 21:32 UTC
## Issue
When running `webpack --watch` with `HappyPack` and `sass-loader`, you have to first modify the top level entry point to make incremental builds work.

## To reproduce

1. Run the [example repo](https://github.com/christianvuerings/happy-repo/) - see main outline below.
1. `webpack --watch`
1. Modify `src/common/include.scss`

### Result
The incremental build doesn't trigger.

### Expected
For the incremental build to trigger.

### Workaround
 - You have to first modify `main.scss` and then `common/include.scss`. After this incremental builds work correctly.
 - Works fine without `HappyPack` but results in way slower builds.

## Example directory structure ([example repo](https://github.com/christianvuerings/happy-repo/))
```
src/
  main.scss
  common/
    include.scss
```

**`main.scss`**
```css
@import "src/common/include.scss"
```

**`common/include.scss`**
```css
body {
  background: #f00;
}
```

**`webpack.config.js`** ([complete webpack.config.js](https://github.com/christianvuerings/happy-repo/blob/master/webpack.config.js))
```
const config = {
  entry: {
    common_desktop: 'src/main.scss',
  },
  loaders: [
    {
      test: /\.scss/,
      loader: ExtractTextPlugin.extract('style', 'happypack/loader?id=sass', {
        allChunks: true
      })
    },
    plugins: [
      new ExtractTextPlugin('[name].css'),
      new HappyPack({
        loaders: ['css?importLoaders=1!sass']
      })
   ]
}
module.exports = config;
```

**Comment by rardoz** [comment] 2017-01-22 10:02
I am also able to repo this and am looking for a potential solution. The @import statements in the sass files do not get updated when making a change.

**Comment by amireh** [comment] 2017-01-22 12:22
This may be related to #118 - it could be a caching issue after-all. However, while I was debugging that issue I came to realize that there's some root issue causing the strangeness in extract-text's behaviour. It's reproducible even without sass-loader or less/postcss/etc. Unfortunately it felt like chasing ghosts and I didn't come close to a solution but I'm hoping that solving that will iron out these bugs as well.

Out of curiosity, does the issue persist if you stop using extract-text?

**Comment by christianvuerings** [comment] 2017-01-23 19:08
@amireh it's also an issue when we remove `extract-text-webpack-plugin`. You can try it out by [commenting out this line](https://github.com/christianvuerings/happy-repo/blob/06eacf7783319f5b8a350e0fa5ec2623469aae7c/webpack.config.js#L35) in the example repo.

We also tried to make a [`CSS-only` version](https://github.com/christianvuerings/happy-repo/blob/css-only/webpack.config.js) without the `sass-loader` but it keeps generating errors with `HappyPack`.

**Comment by motin** [comment] 2017-01-24 12:07
Same here with less-loader and extract-text-webpack-plugin. The workaround is to manually modify the parent less file every time an imported less file has changed.

**Comment by MrFrankel** [comment] 2017-07-11 13:00
Any news on this? less is really killing my build time and Id love to pipe them though happypack

**Comment by amireh** [comment] 2017-07-11 13:28
Is it any different with v4 of happypack since caching was removed?

**Comment by MrFrankel** [comment] 2017-07-11 14:13
@amireh seems to be fixed!! thanks a bunch! I am a happy pack happy user :)

**Comment by amireh** [comment] 2017-07-11 14:30
hahaha, glad to hear! Can we close this then ? Or wait until 4 is out of beta status?

**Comment by MrFrankel** [comment] 2017-07-11 17:20
as for me this can be closed

**Closed** 2017-07-14 21:19 UTC
Labels: bug
