### ISSUE TITLE
__webpack_require__(...) is not a function, when use with extract-text-webpack-plugin

### ISSUE THREAD

**Issue by frankLife** [amireh/happypack#92] opened 2016-09-21 13:50 UTC
![](http://gw.alicdn.com/tfs/TB1RwaONpXXXXXRXpXXXXXXXXXX-1180-282.png)
1. when use with extract-text-webpack-plugin
2.  just config the js loader
3. same project, 30% of cases will come across this.
4. happen when many `import` function in less file

What & How to make this error?

How to fix or ignore this ?

**Comment by frankLife** [comment] 2016-10-12 06:17
@amireh may you give us some ideas ?

**Comment by amireh** [comment] 2016-10-12 08:05
I don't know man, extract-text plugin has many quirks and it takes too much time to debug. Make sure you're getting the configuration correctly (verify that it's all working _without_ happypack first!)

Consider using extract-text only in production and forget it during development. They have plans to rewrite that plugin in webpack 2+ so it should be a temporary thing.

**Comment by frankLife** [comment] 2016-10-16 08:16
When this happen , it just remove the part of config of happypack and everything just will be ok. 
I know it's hard work out and I am also working on this. 
Thank you anyway :)

**Comment by frankLife** [comment] 2016-11-14 14:26
Little progress :)

![](http://gw.alicdn.com/tfs/TB1m2kvOXXXXXaKapXXXXXXXXXX-1480-433.png)

In the callback of `runAsChild`,  the css-loader's css-base.js is empty, So it would fail.

The` css-base.js` file is compiled by happypack worker .

I guess that the runAsChild will trigger the process of happypack loader logic,but the css-loader is not in that multi process logic . so it may be fail .

Do you have any idea ? @amireh

**Comment by frankLife** [comment] 2016-11-15 08:01
When config the extract-text-plugin, it seems not to happen ..

**Comment by amireh** [comment] 2016-11-18 13:27
Hmm, that sounds like a bug on happypack's end.

How can we reproduce this? Can you set up an example repository that I can look at?

**Comment by frankLife** [comment] 2016-11-19 07:57
I think I got this.
I find when many threads run (16 threads). it would happen that a same file is being writed when it is being read by a another one by a same compile path when the read process  dosen't finish and cache object has not been set .

I try to fix this by modify compiledPath generate function like this 

```

exports.generateCompiledPath = function(filePath) {
  if (process.env.DEBUG) {
    return filePath.replace(/\W+/g, '_');
  }
  else {
    return 's-' + hashString(filePath + Math.random().toString(36).substr(2));
  }
};
```

to ensure every file has a unique path when cache is not set , the error just go away :)

If you think this is reasonable，I appreciate producing a better pr ~ @amireh

**Comment by frankLife** [comment] 2016-12-03 13:02
@amireh  
How do you think ?

**Comment by amireh** [comment] 2016-12-03 15:46
Thanks for investigating @frankLife - I'm not sure if this is the right solution, because if there's a race condition around accessing the cache object (which, if I'm understanding the issue correctly, seems to be the case) then I think we need to install proper guards around it. It just might be that with this fix, we'll come across other subtle issues like these.

It would be tremendously helpful if you can get me an example / steps to reproduce this, then I can lend a hand. Otherwise I'm not sure I can help much here, if your fix makes it work for you, we can merge that, but I'd rather we fix the root issue here.

Thanks again.

**Comment by frankLife** [comment] 2016-12-04 06:17
We modified the filepath generate function  like that and it works for some time since last comment here . 
But I think it's hard to give a example to reproduce it because it needs environment support . But  I will give your more detail explain to make you understand it . 
Happypack is great project that  improve our assets build work  ：）

**Comment by amireh** [comment] 2016-12-04 08:06
Ok, I've just incorporated that fix into the codebase and released version 3.0.1 that includes it. :tada: 

Judging by the code you inserted here, I believe you're on the 2.x version so I'm afraid you need to upgrade. There are instructions in the CHANGELOG but I hope it won't be painful.

Please let me know if there's anything else.

**Comment by frankLife** [comment] 2016-12-15 09:44
Thanks! I think we can upgrade 3.x version .

The key to this case is that two or more workers compile the same file before updating the cache.

```
  worker.compile({
    loaders: this.state.loaders,
    compiledPath: path.resolve(this.config.tempDir, HappyUtils.generateCompiledPath(filePath)),
    loaderContext: loaderContext,
  }, function(result) {
    var contents = fs.readFileSync(result.compiledPath, 'utf-8')
    var compiledMap;

    if (!result.success) {
      cache.updateMTimeFor(filePath, null, contents);
      done(contents);
    }
    else {
      cache.updateMTimeFor(filePath, result.compiledPath);
      compiledMap = SourceMapSerializer.deserialize(
        fs.readFileSync(cache.getCompiledSourceMapPath(filePath), 'utf-8')
      );

      done(null, contents, compiledMap);
    }
  });
```
The error happens with a worker invoke the function of `fs.readFileSync` before updating the cache . the readed content is empty string.

For example, There are two wokers are compiling the same file because there is not any process which is finished. The wokerA is reading file content whereas workerB is writing file in the same path . then reading process error may occur.

Like this case [stackoverflow](http://stackoverflow.com/questions/10368806/node-js-readfile-woes)

I hope it may help you :) @amireh

**Comment by amireh** [comment] 2016-12-20 11:50
@frankLife we've introduced a regression with this change since `generateCompiledPath` is no longer pure which is making the cache grow uncontrollably since each input file path is now producing a (potentially) different compiled file path.

Why are two workers trying to compile _the same file_? It seems this is the root issue. Can you at least show the config you're using to reproduce the issue?

**Comment by frankLife** [comment] 2016-12-28 16:25
The config is normal as demo. The key is before ` cache.updateMTimeFor(filePath, result.compiledPath);` the file hasn't been recognized as compiled completely ,So there would be a another worker to compile the file.

**Comment by frankLife** [comment] 2017-02-15 06:35
@amireh  I have taken a look at this #115  . I think this good change can fix the problem that it will result in redundant cache file path for the same file between two compile process.

The random path is aim to deal with the same file would be requested many times before it's information would be saved into cache object(or file) by different worker.Util now, we haven't come across the question mentioned before in our team's compile tool chain.

**Comment by amireh** [comment] 2017-06-01 20:11
In the light of the change in v4 that [drops caching from happypack](https://github.com/amireh/happypack/blob/master/CHANGELOG.md#400), this ticket is no longer applicable so I'll be closing it. Please feel free to re-open if the issue persists (i.e. it's not related to caching.)

**Closed by amireh** 2017-06-01 20:11 UTC
Labels: bug, needs context
