### ISSUE TITLE
Not faster.

### ISSUE THREAD

**Issue by gibson** [amireh/happypack#144] opened 2017-03-17 07:43 UTC
```javascript 
plugins:    [
    new HappyPack({
      id:         'js',
      loaders:    ['babel'],
      threadPool: happyThreadPool,
      cache: true,
      debug: true
    }),
    new HappyPack({
      id:         'sass',
      loaders:    [`style-loader!css-loader?localIdentName=[path][name]__[local]--[hash:base64:5]&sourceMap=inline!postcss-loader?sourceMap=inline!sass-loader?sourceMap=inline&includePaths=${pathTo('src')}`],
      threadPool: happyThreadPool,
      cache: true
    })
]
 loaders: [
      {
        test:    /\.(jsx|js)?$/,
        exclude: /node_modules/,
        loader:  'happypack/loader?id=js'
      },
      {
        test:   /\.s?css$/,
        loader: 'happypack/loader?id=sass'
      }
]
```
Speed before ~23s after ~22s
Incremental not changed ~3-5s
Core i5 (4 cores)
Threadpool = 4
ssd

```
Happy[js]: Loaded 653 entries from cache. (0 were stale)
Happy[js]: All set; signalling webpack to proceed.
Happy[sass]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[sass]: Loaded 221 entries from cache. (0 were stale)
Happy[sass]: All set; signalling webpack to proceed.
webpack building...
webpack built 933e8ee0f7f21642554e in 21738ms
```

**Comment by aramk** [comment] 2017-04-18 13:34
I'm seeing a similar result. I've configured the plugins and I'm seeing Happypack logs as files are being built, but if I monitor the `node` processes I can see that only one is being used at 100% CPU while the others are always idle. Not sure if https://github.com/amireh/happypack/issues/111 is related. @amireh would you be able to comment on any potential issues? I'm running webpack^2.4.1 with happypack^3.0.3.

**Comment by amireh** [comment] 2017-04-18 14:57
Hmm, it could be a number of things. First, I'm not sure if 600 modules is enough to see the benefit although we _did_ receive reports of improvement on such numbers but this was back with webpack 1.

Which OS and which node version is this happening on? The CPU profile is interesting, can we get screenshots or a small case to reproduce?

We've switched to webpack 2 on a big project at work and we did see a minor performance decrease but nothing close to what you're reporting. I just assumed webpack 2 has a higher overhead and never investigated since I don't have much time for this anymore.

**Comment by aramk** [comment] 2017-04-19 00:57
I have the following run for around 900 modules. I'm not seeing any further logging for Happypack despite having verbose and debug enabled.

```
> webpack --config config/webpack/prod.webpack.config.js --progress

Happy[js]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[js]: Loaded 42 entries from cache. (0 were stale)
Happy[js]: All set; signalling webpack to proceed.
Happy[html]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[html]: Loaded 122 entries from cache. (0 were stale)
Happy[html]: All set; signalling webpack to proceed.
Happy[sass]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[sass]: Loaded 1 entries from cache. (0 were stale)
Happy[sass]: All set; signalling webpack to proceed.
Hash: 319aa06b340124042072
Version: webpack 2.4.1
Time: 36563ms
```

I can see only one process is being utilised:

<img width="443" alt="screen shot 2017-04-19 at 10 55 54 am" src="https://cloud.githubusercontent.com/assets/574282/25158871/e379bb2c-24ee-11e7-88e4-207a9c475989.png">

My configuration is like this:

```
const srcLoader = {
  test: helpers.pathRegEx(/src\/.*\.(js|jsx)$/),
  use: 'happypack/loader?id=js',
  include: [path.resolve(basePath, 'src')]
};
config.module.rules.push(srcLoader);

const sassLoader = {
  test: helpers.pathRegEx(/\.scss$/),
  use: extractCSSTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader',
      {
        loader: 'resolve-url-loader',
        // NOTE: Enable this to provide detailed logging for all files requested in SASS files.
        // options: {
        //   debug: true
        // }
      },
      {
        loader: 'postcss-loader',
        options: {
          plugins() {
            return [
              autoprefixer({
                browsers: [
                  'last 1 version'
                ]
              })
            ]
          }
        }
      },
      {
        loader: 'happypack/loader?id=sass'
      }
    ]
  })
};
config.module.rules.push(sassLoader);

const htmlLoader = {
  test: /\.html$/,
  exclude: /index-template.html$/,
  use: 'happypack/loader?id=html'
};
config.module.rules.push(htmlLoader);

config.plugins.push(new HappyPack({
  id: 'js',
  cache: true,
  verbose: true,
  debug: true,
  loaders: [
    {
      loader: 'babel-loader',
      babelLoaderArgs
    }
  ],
  threadPool: happyThreadPool
}));

config.plugins.push(new HappyPack({
  id: 'html',
  cache: true,
  verbose: true,
  debug: true,
  loaders: [
    {
      loader: 'html-loader',
      options: {
        minimize: true,
        removeAttributeQuotes: false,
        caseSensitive: true,
        customAttrSurround: [ [/#/, /(?:)/], [/\*/, /(?:)/], [/\[?\(?/, /(?:)/] ],
        customAttrAssign: [ /\)?\]?=/ ]
      }
    }
  ],
  threadPool: happyThreadPool
}));

config.plugins.push(new HappyPack({
  id: 'sass',
  cache: true,
  verbose: true,
  debug: true,
  loaders: [
    {
      loader: 'sass-loader',
      options: {
        // TODO(aramk) This is essential for resolving file references, but may be slowing down the build.
        sourceMap: true,
        includePaths: includedSassPaths
      }
    }
  ],
  threadPool: happyThreadPool
}));
```

**Comment by amireh** [comment] 2017-04-19 06:03
A few things worth noting:

- the total module count (at least what happypack is seeing) seems to be 165, and from that log they're already compiled and cached
- you aren't properly passing options to your babel loader. I'm not sure what `babelLoaderArgs` is but it seems like you're destructuring it and that's not a valid key. You need to pass `options` or `query` like you do for webpack `module.rules`.
- i haven't tested with extract-text in webpack2, we've had troubles with that plugin in webpack1 and usually you don't want to use it in development

Try removing your happypack cache then run it again and you should see some output I think. `rm -r .happypack` should do that.

**Comment by aramk** [comment] 2017-04-24 10:18
I fixed the issue with my destructuring and removed the cache and I can see logs for Happypack, but I'm still seeing no parallelisation :(

**Comment by luisgrases** [comment] 2017-04-25 07:11
+1

**Comment by AStaroverov** [comment] 2017-04-25 18:01
Not faster for me :( i'm use it for only js+jsx files with babel loader with webpack 2

**Comment by luisgrases** [comment] 2017-04-25 19:12
I have tried to use it on js+jsx files and also using it with scss files too. I am using webpack 1.14 and I have a Macbook Pro 13 retina. So far not getting any better build times.

**Comment by amireh** [comment] 2017-04-25 19:58
It's impossible to make any assessment without actual facts like:

- how many modules are there?
- which node version?
- which OS?
- how many threads? using a thread pool?
- how many loaders and which loaders?

Keep in mind that we haven't even considered using parallelization (happypack) until our build started containing more than 2500 modules. There is an overhead to webpack's compilation itself that will most likely overshadow any benefits you get from parallelization if the number of modules is below a certain threshold, and that overhead seems to be larger in webpack 2 hence my earlier comments (but I have no proof for this yet, it's all just speculation.)

**Comment by aramk** [comment] 2017-04-25 23:57
Hmm ok, I can provide some more information and maybe compare with @AStaroverov.

* 1000 modules
* Node 6.9.1
* macOS 10.12.4
* 4 threads in a thread pool
* The loaders I shared above (babel, sass, text, fonts, images)

I ended up going the https://github.com/trivago/parallel-webpack way and I can build styles and scripts in parallel, but it doesn't support the dev-server and I had to use the --watch option and https://github.com/tapio/live-server and some other quirks to get it working.

**Comment by AStaroverov** [comment] 2017-04-26 08:00
* ~2200 modules
* node 7.8.0
* Ubuntu 14.04
* 4 threads
* one babel-loader for .jsx?$

**Comment by RavenHursT** [comment] 2017-04-27 00:50
@amireh  I'm seeing about 17% improvements over our non-happypack build.. but what I'm not seeing, is any kind of improvement w/ the caching in happypack itself... 

I'm seeing happypack report that it's using cache.. but the time it takes to run through webpack builds is exactly the same

```
Happy[jsx]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[jsx]: Loaded 215 entries from cache. (0 were stale)
Happy[jsx]: All set; signalling webpack to proceed.
Happy[json]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[json]: Loaded 28 entries from cache. (0 were stale)
Happy[json]: All set; signalling webpack to proceed.
Happy[null-loader]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[null-loader]: Loaded 0 entries from cache. (0 were stale)
Happy[null-loader]: All set; signalling webpack to proceed.
===== JS file Generation Completed
===== Generating CSS For Themes =====
Happy[sass]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[sass]: Loaded 20 entries from cache. (4 were stale)
Happy[sass]: All set; signalling webpack to proceed.
Happy[css]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[css]: Loaded 0 entries from cache. (0 were stale)
Happy[css]: All set; signalling webpack to proceed.
Happy[file-loader]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[file-loader]: Loaded 54 entries from cache. (0 were stale)
Happy[file-loader]: All set; signalling webpack to proceed.
Happy[null-loader]: Version: 3.0.3. Using cache? yes. Threads: 4 (shared pool)
Happy[null-loader]: Loaded 0 entries from cache. (0 were stale)
Happy[null-loader]: All set; signalling webpack to proceed.
```

Any ideas?

**Comment by amireh** [comment] 2017-08-26 21:46
Not sure what to do with this guys so I'll be closing this. If you find a specific issue that we can address, please open an issue for it. Thanks

**Closed by amireh** 2017-08-26 21:46 UTC
