### ISSUE TITLE
Happy id with query property in loader fails

### ISSUE THREAD

**Issue by beckend** [amireh/happypack#26] opened 2016-04-10 16:11 UTC
Using: 

```
        {
          test:    /.js$/,
          exclude: /node_modules/,
          loader:  'babel',
          query:   babelrcJsonFileToObject,
          happy:   { id: 'babelJs' }
        }
...
       plugins: [
          new HappyPack({ id: 'babelJs' }),
       ]

```
Fails with: 
```
Module build failed: AssertionError: HappyPack: plugin for the loader 'babelJs?{"presets":["es2015-webpack","react","stage-0"],"plugins":["transform-runtime","transform-decorators-legacy","jsx-control-statements",["typecheck",{"disable":{"production":true}}]],"env":{"test":{"presets":["es2015-webpack","react","stage-0"],"plugins":["transform-runtime","transform-decorators-legacy","jsx-control-statements",["typecheck",{"disable":{"production":true}}]]},"browser":{"presets":["es2015-webpack","react","stage-0"],"plugins":["transform-runtime","transform-decorators-legacy","jsx-control-statements",["typecheck",{"disable":{"production":true}}],["react-transform",{"transforms":[{"transform":"react-transform-hmr","imports":["react"],"locals":["module"]},{"transform":"react-transform-catch-errors","imports":["react","redbox-react"]}]}]]},"production":{"presets":["es2015-webpack","react","stage-0"],"plugins":["transform-runtime","transform-decorators-legacy","jsx-control-statements","transform-flow-strip-types","react-remove-prop-types"]}}}'

could not be found! Did you forget to add it to the plugin list?
```

**Comment by beckend** [comment] 2016-04-10 16:16
With:
```
        {
          test:    /.js$/,
          exclude: /node_modules/,
          loader:  'babel' + JSON.stringify(babelrcJsonFileToObject),
          // query:   babelrcJsonFileToObject,
          happy:   { id: 'babelJs' }
        }
```
It seems to work just fine.

**Comment by beckend** [comment] 2016-04-10 18:12
On further testing, the options seems to be flaky when passed in by JSON.stringify, the plugins were kinda messed up, on a production build I got HMR included and error, which does not happen using query property.

**Comment by amireh** [comment] 2016-04-10 20:13
I think this is a problem with the new configuration syntax. Can you try using the "regular" way to configure the loader and see if it makes any difference? Something like this:

```javascript
module.exports = {
  module: {
    loaders: [{
      test: /.js$/,
      loader: 'happypack/loader?id=babelJs',
      exclude: /node_modules/
    }],
  },
  plugins: [
    new HappyPack({
      id: 'babelJs',
      loaders: [ 'babel' ]
    })
  ]
};
```

BTW, you don't really need to specify babel's options in the query if you have a `.babelrc` file, you should just be able to omit the query altogether. Did you try that?

**Comment by beckend** [comment] 2016-04-10 20:57
That worked, but I do conditional stuff on babelrc in the config, that is why.

**Comment by amireh** [comment] 2016-04-10 21:10
And specifying the query with that configuration still doesn't work? It should pass it just fine as long as it is `JSON.stringify()`-able. How does webpack do it then? Is there a custom serializer for this query option? I don't think I've seen it before.

You could try manually serializing the object to a query string, using something like [query-string](https://www.npmjs.com/package/query-string)?

```javascript
var queryString = require('query-string');

  // ...
  plugins: [
    new HappyPack({
      id: 'babelJs',
      loaders: [{ path: 'babel', query: queryString.stringify(customBabelRc) }]
    })
  ]
```

**Comment by beckend** [comment] 2016-04-10 21:33
With:
```
          loader: 'happypack/loader?id=babelJs',

...

and your copy paste code from above:

Happy[babelJs]: Version: 2.0.3. Using cache? yes. Threads: 3
fatal watch error!!! { [Error: Can't resolve 'babelenv=%5Bobject%20Object%5D&plugins=jsx-control-statements&plugins=transform-decorators-le.......................
```

Exact same thing without stringify:

```
ersion: 2.0.3. Using cache? yes. Threads: 3
fatal watch error!!! { [Error: Can't resolve 'babel[object Object]'..............
```

**Comment by cpsubrian** [comment] 2016-04-26 07:13
According to https://gist.github.com/sokra/27b24881210b56bbaff7#loaders-configuration using the `query` object like @beckend is trying to do is both valid and recommended by several blog posts I've read recently. Would be nice if it worked 'out of the box'.

FWIW, though, `JSON.stringify()` worked for my particular configuration, as it seems to be what webpack does anyway. https://github.com/webpack/webpack/blob/b0fffd50d35dd0eef734d189928c1ac4c5c9fb97/lib/LoadersList.js#L42-L47

**Comment by amireh** [comment] 2016-04-26 07:31
Huh, that is really strange, I would have expected `query` to be serialized as a query string, not JSON! I had started on this and used the [query-string](https://www.npmjs.com/package/query-string) module for serializing the object and it seemed to work. Now, I'm not sure what's the right thing to do.

**Comment by cpsubrian** [comment] 2016-04-26 07:41
@amireh Take this with a grain of salt, as I don't know webpack's internals at all, but perhaps its wrong to think of loaders as 'urls', really they are `require` paths that get resolved based on `resolveLoader` config. The `query` part is probably just a cute naming convention for stringified configuration. They probably just try to JSON.parse it and failing that split it like a url. Think about it, its not like these are ever requested by an actual server or anything, its all internal to the webpack CLI. Just my guess anyhow 😄

**Comment by amireh** [comment] 2016-04-26 08:09
My god, you're right! https://github.com/webpack/loader-utils/blob/master/index.js#L73-L75

I never really gave it much thought, but the name `query` is misleading to say the least. Thanks for chipping in, this helped a lot :)

**Comment by amireh** [comment] 2016-04-26 08:18
Pinging @beckend, @cpsubrian, @aaronshaf to try #37 out and see if it fixes your use cases.

**Comment by beckend** [comment] 2016-04-26 08:37
Sorry for the noise, it was clumsy, should've just used the branch you made.
So I gave it a spin, with happypack I still got HMR on production build, when disabled it works fine.

**Comment by amireh** [comment] 2016-04-26 08:44
@beckend no problem. Is that an affirmative? What's the expected behavior for you?

**Comment by beckend** [comment] 2016-04-26 08:48
So let just make things clear, I'm using query, which contains a babel json converted to a javascript object. I have always used this and it does not add HMR on my production builds.

The expected behaviour is that builds with or without happypack should be identical(but faster with happypack of course).

**Comment by amireh** [comment] 2016-04-26 08:56
Ok, thanks for explaining.

What's happening might be unrelated to the query options per se, more like what webpack passes in prod mode; maybe there are some flags I'm missing as that has happened before. 

There's also the fact that we're not yet populating `this.options` for loaders, which could be it. webpack automatically injects into each loader any config that is specified by its name, so for `babel-loader`, it would look for `compiler.options.babel` and pass that to the babel loader which can then access as `this.options`.

To go forward, I think I need some sample configs to work with, otherwise I'm stabbing in the dark.

**Comment by beckend** [comment] 2016-04-26 09:10
Currently using:
```
{
  "presets": [ "es2015", "react", "stage-0" ],
  "plugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    "jsx-control-statements",
    "add-module-exports",
    ["typecheck", { "disable": { "production": true } }]
  ],
  "env": {
    "test": {
      "presets": [ "es2015-webpack", "react", "stage-0" ],
      "plugins": [
        "transform-runtime",
        "transform-decorators-legacy",
        "jsx-control-statements",
        "add-module-exports",
        ["typecheck", { "disable": { "production": true } }]
      ]
    },
    "browser": {
      "presets": [ "es2015-webpack", "react", "stage-0" ],
      "plugins": [
        "transform-runtime",
        "transform-decorators-legacy",
        "jsx-control-statements",
        "add-module-exports",
        ["typecheck", { "disable": { "production": true } }],
        ["react-transform", {
          "transforms": [
            {
              "transform": "react-transform-hmr",
              "imports": [ "react" ],
              "locals": [ "module" ]
            },
            {
              "transform": "react-transform-catch-errors",
              "imports": [ "react", "redbox-react" ]
            }
          ]
        }]
      ]
    },
    "production": {
      "presets": [ "es2015-webpack", "react", "stage-0" ],
      "plugins": [
        "transform-runtime",
        "transform-decorators-legacy",
        "jsx-control-statements",
        "add-module-exports",
        "transform-flow-strip-types",
        "react-remove-prop-types"
      ]
    }
  }
}

```

You don't have to use that many modules, the key is point is that I don't have react-transform plugin and typecheck etc in the "production" env.

You can simply change the env in babel by setting `process.env.BABEL_ENV = 'production'`.

I would love to share my project with you but it's not open source and the webpack config/deps are huge.

I don't quite know what webpack 2 does exactly on production, it's using a new plugin `LoaderOptionsPlugin` to minimize assets.
It's in this gist: https://gist.github.com/sokra/27b24881210b56bbaff7
at "Loader options & minimize".

**Comment by mmahalwy** [comment] 2016-05-09 18:20
heads up, I cannot get this to work, error:
```
fatal watch error!!! { [Error: Can't resolve 'babel[object Object]' in '/Users/mmahalwy/Sites/sparrow']
  details: 'resolve \'babel[object Object]\' in \'/Users/mmahalwy/Sites/sparrow\'\n  Parsed request is a module\n  using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: .)\n  after using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: .)\n    resolve as module\n      module variation babel[object Object]-loader\n        /Users/mmahalwy/Sites/node_modules doesn\'t exist or is not a directory\n        /Users/mmahalwy/node_modules doesn\'t exist or is not a directory\n        /Users/node_modules doesn\'t exist or is not a directory\n        /node_modules doesn\'t exist or is not a directory\n        looking for modules in /Users/mmahalwy/Sites/sparrow/node_modules\n          using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: ./node_modules)\n          after using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: ./node_modules)\n            using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: ./node_modules/babel[object Object]-loader)\n              as directory\n                /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader doesn\'t exist\n              no extension\n                /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader doesn\'t exist\n              .js\n                /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader.js doesn\'t exist\n              .json\n                /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader.json doesn\'t exist\n      /Users/mmahalwy/Sites/node_modules doesn\'t exist or is not a directory\n      /Users/mmahalwy/node_modules doesn\'t exist or is not a directory\n      /Users/node_modules doesn\'t exist or is not a directory\n      /node_modules doesn\'t exist or is not a directory\n      looking for modules in /Users/mmahalwy/Sites/sparrow/node_modules\n        using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: ./node_modules)\n        after using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: ./node_modules)\n          using description file: /Users/mmahalwy/Sites/sparrow/package.json (relative path: ./node_modules/babel[object Object])\n            as directory\n              /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object] doesn\'t exist\n            no extension\n              /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object] doesn\'t exist\n            .js\n              /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object].js doesn\'t exist\n            .json\n              /Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object].json doesn\'t exist',
  missing:
   [ '/Users/mmahalwy/Sites/node_modules',
     '/Users/mmahalwy/Sites/node_modules',
     '/Users/mmahalwy/node_modules',
     '/Users/mmahalwy/node_modules',
     '/Users/node_modules',
     '/Users/node_modules',
     '/node_modules',
     '/node_modules',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader.js',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]-loader.json',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object]',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object].js',
     '/Users/mmahalwy/Sites/sparrow/node_modules/babel[object Object].json' ] }
/Users/mmahalwy/Sites/sparrow/node_modules/webpack-dev-middleware/middleware.js:106
			if(err) throw err;
			        ^

Error: Can't resolve 'babel[object Object]' in '/Users/mmahalwy/Sites/sparrow'
    at onResolved (/Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/Resolver.js:64:16)
    at loggingCallbackWrapper (/Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/Resolver.js:136:10)
    at loggingCallbackWrapper (/Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Tapable.applyPluginsAsyncSeriesBailResult1 (/Users/mmahalwy/Sites/sparrow/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/Resolver.js:123:19)
    at loggingCallbackWrapper (/Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/mmahalwy/Sites/sparrow/node_modules/tapable/lib/Tapable.js:210:15
    at /Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/Users/mmahalwy/Sites/sparrow/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
```

with config:
```
module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, happy: {id: 'js'}, loaders: [
        {
          path: 'babel',
          loader: 'babel',
          query: {
            plugins: [
              'transform-runtime',
              'add-module-exports',
              'transform-decorators-legacy',
              'transform-react-display-name',
              'system-import-transformer',
              'typecheck',
            ],
            presets: ['react', 'es2015-webpack', 'stage-0', 'react-hmre'],
            cacheDirectory: true
          }
        },
        'eslint-loader'
      ]},
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.scss$/, loader: 'happypack/loader?id=scss'},
      { test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/font-woff" },
      { test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/font-woff" },
      { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
      { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
      { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" },
      { test: webpackIsomorphicToolsPlugin.regular_expression('images'), loader: 'url-loader?limit=10240' }
    ]
  },
  progress: true,
  resolve: {
    modules: [
      'src',
      'node_modules'
    ],
    extensions: ['', '.json', '.js']
  },
  plugins: [
    // hot reload
    new HappyPack({ id: 'js'}),
    new HappyPack({ id: 'scss', loaders: ['style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap'] }),
```

**Comment by todd-richmond** [comment] 2016-07-03 00:03
JSON.stringify works for me w/ latest happypack release whereas a separate query key has the problem listed here - thx

**Comment by amireh** [comment] 2016-08-05 19:22
This should be fixed in the 2.1.3 release, please re-open if you find out otherwise.

**Closed by amireh** 2016-08-05 19:22 UTC
Labels: bug

**Comment by keller35** [comment] 2016-12-16 08:12
did the fix works? I still got an error when using query in loader:

```
ERROR in ./wap/global/entry.js
Module build failed: AssertionError: HappyPack: plugin for the loader 'babel?{"presets":["react"' could not be found! Did you forget to add it to the plugin list?
    at Object.HappyLoader (/Users/keller/youzan/store/node_modules/happypack/lib/HappyLoader.js:25:3)
```

and here is my webpack config:
```
    plugins: [
        new HappyPack({
            id: 'babel',
            loaders: ['babel?presets[]=react&'],
            threadPool: happyThreadPool,
            cache: true,
            verbose: true
        })
   ].

   loaders: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loader: ['happypack/loader?id=babel'],
                query: {
                    presets: ['react', 'es2015', 'stage-2'],
                    plugins: ['transform-object-assign']
                }
            }
    ]
```

**Comment by amireh** [comment] 2016-12-16 08:28
You're still passing query to _happypack's loader_ instead of babel. Remove `query: {}` from the object passed to `loaders: []` and define your babel config in the happypack plugin:

```javascript
{
    plugins: [
        new HappyPack({
            id: 'babel',
            loaders: [{
                path: 'babel',
                query: {
                    presets: ['react', 'es2015', 'stage-2'],
                    plugins: ['transform-object-assign']
                }
            }],
            threadPool: happyThreadPool,
            cache: true,
            verbose: true
        })
   ].

   loaders: [
        {
            test: /\.(js|jsx)$/,
            exclude: /node_modules/,
            loader: ['happypack/loader?id=babel'],                
        }
    ]
}
```

**Comment by rroslaniec** [comment] 2017-01-03 09:47
I have similar issue as @keller35

```
plugins: [
    new HappyPack({
        id: 'babel',
        loaders: [{
            path: 'babel-loader',
            query: {
                presets: ['react', 'es2015', 'stage-2', { modules: false }],
                plugins: ['transform-object-assign']
            }
        }],
        threads: 4,
        cache: true,
        verbose: true
    })
],
module: {
  loaders: [{
    {
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'happypack/loader?id=babel',
    }
...
```

with error

```
> example@0.0.0 start /home/rroslaniec/work/example
> babel-node server

/home/rroslaniec/work/example/node_modules/happypack/loader.js
Happy[babel]: Version: 3.0.2. Using cache? yes. Threads: 4
==> Compiling. Wait for message: "webpack: bundle is now VALID."
==> 🌎 Listening on port 3000. Open up http://localhost:3000/ in your browser.
Happy[babel]: Cache is no longer valid, starting fresh.
Happy[babel]: All set; signalling webpack to proceed.
webpack building...
webpack built 92264859225ba5c2c37e in 3645ms
Version: webpack 2.2.0-rc.3
     Asset     Size  Chunks  Chunk Names
 mobile.js  1.03 MB       0  mobile
desktop.js  1.03 MB       1  desktop
chunk    {0} mobile.js (mobile) 324 kB [entry] [rendered]
chunk    {1} desktop.js (desktop) 324 kB [entry] [rendered]

ERROR in ./app/desktop.js
Module parse failed: /home/rroslaniec/work/example/node_modules/happypack/loader.js?id=babel!/home/rroslaniec/work/example/app/desktop.js Unexpected token (34:2)
You may need an appropriate loader to handle this file type.
| 
| ReactDOM.render(
|   <Application url={location.pathname + (location.search || '')} />,
|   document.getElementById('root')
| );
 @ multi desktop

ERROR in ./app/mobile.js
Module parse failed: /home/rroslaniec/work/example/node_modules/happypack/loader.js?id=babel!/home/rroslaniec/work/example/app/mobile.js Unexpected token (34:16)
You may need an appropriate loader to handle this file type.
| }
| 
| ReactDOM.render(<Application url={location.pathname + (location.search || '')} />, document.getElementById('root'));
| 
| if (module.hot) {
 @ multi mobile
```


Dependencies:

```
    "webpack": "^2.2.0-rc.3",
    "babel-core": "6.21.0",
    "babel-loader": "6.2.10",
```

**Comment by GuillaumeCisco** [comment] 2017-01-03 14:58
@amireh Your last post made it for me!!! Thank you! Using:
- happypack 3.0.2
- webpack 1.14.0
- babel-core 6.21.0
- babel-loader 6.2.10

But I spent nearly an hour finding how to configure it.
Adding a line in the README would be great!

**Comment by amireh** [comment] 2017-01-03 15:40
@GuillaumeCisco Glad it worked!

> But I spent nearly an hour finding how to configure it.

What exactly didn't you find?

> EDIT: Drawback is HMR does not work anymore :/

We've been using HMR without a problem (for css and for react with react-hot-loader and webpack-hot-middleware), it's possibly a config issue. What are you using?

**Comment by GuillaumeCisco** [comment] 2017-01-03 15:55
Thanks @amireh.
Indeed it was a config issue, forgot to readd `react-hmre` to my presets.

My new code for helping others is :
```javascript
const DEVELOPMENT = (['development', 'staging'].includes(process.env.NODE_ENV)),
         PRODUCTION = (['production'].includes(process.env.NODE_ENV));

export default {
     /* basic config */
     module: {
            loaders: [{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'happypack/loader?id=babel',
           },], 
           /* others loaders */
     },
     plugins: [
        new HappyPack({
            id: 'babel',
            loaders: [{
                path: 'babel-loader',
                // Options to configure babel with
                query: {
                    plugins: [
                        'transform-runtime',
                        ...(PRODUCTION ? [
                            "transform-react-constant-elements",
                            "transform-react-inline-elements",
                            "transform-react-remove-prop-types"
                        ] : [])
                    ],
                    presets: [
                        "es2015",
                        "react",
                        "stage-0",
                        ...(DEVELOPMENT ? ['react-hmre'] : [])
                    ]
                },
            }],
            threads: 4,
        }),
    /* others plugins */
    ],       
}
```

But weirdly I add to run twice happy-pack (I think), need more tests.
But now it works perfectly :)

The thing I could not find is  :how to write the Happy Pack plugin in a object manner with path and query parameters :)

Thank you again.

**Comment by keller35** [comment] 2017-01-20 03:09
@GuillaumeCisco 
`react-hmre`is presently not maintaine so i change to using [react-hot-loader](https://github.com/danmartinez101/babel-preset-react-hmre).
The problem is that this seems to not working for me and there is no error output.
Do you have any idea?

**Comment by GuillaumeCisco** [comment] 2017-01-20 08:55
Hey @keller35 , I don't know how react-hot-loader workss, but have you tried putting 'react-hot' in the presets list?

Sorry if I'm out of scope.

**Comment by ilearnio** [comment] 2017-06-15 09:06
I have some problems with `id` property. I have set it up properly as described in the docs but I'm seeing this error message:

```
Module build failed: AssertionError [ERR_ASSERTION]: HappyPack: plugin for the loader '1' could not be found! Did you forget to add it to the plugin list?
    at Object.HappyLoader (/Users/Admin/Code/boxes/tradeshow-web/node_modules/happypack/lib/HappyLoader.js:26:3)
```

Why it says `plugin for the loader '1'` if I'm setting ids explicitly for every loader?

```
module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.(vue|js)$/,
        loader: 'happypack/loader?id=eslint',
        exclude: /node_modules/,
        options: {
          formatter: eslintFiendlyFormatter
        }
      },
      {
        test: /\.js$/,
        loader: 'happypack/loader?id=babel',
        include: [
          path.resolve(__dirname, '../src'),
          /shared-web/
        ]
      }
  }
},
plugins: [
    new webpack.EnvironmentPlugin(Object.keys(env)),
    new HappyPack({
      id: 'babel',
      loaders: [ 'babel-loader' ],
      verbose: true
    }),
    new HappyPack({
      id: 'eslint',
      loaders: [ 'eslint-loader' ],
      verbose: true
    })
  ]
```
