### ISSUE TITLE
Common ThreadPool for MultiCompiler webpack builds

### ISSUE THREAD

**Issue by hgenru** [amireh/happypack#82] opened 2016-09-12 16:24 UTC
I allocated ThreadPool by CPU count, but when i use same thread pool for different MultiCompiler build happypack start fine and working in background (I do not know how well), but no output to console.

**Comment by amireh** [comment] 2016-09-15 07:03
I think this is a duplicate of #72.

**Comment by amireh** [comment] 2016-10-11 17:52
Will close this in favor of #72 and follow the progress there.

**Closed by amireh** 2016-10-11 17:52 UTC
