### ISSUE TITLE
vue-loader support

### ISSUE THREAD

**Issue by taoche** [amireh/happypack#83] opened 2016-09-13 01:45 UTC
use happypack for vue-loader..
has error "sass/css can't reslove"

Could you step support "vue-loader"  please?

**Comment by amireh** [comment] 2016-11-07 11:06
Can you please provide a sample config and error details? I'm not familiar with "vue".

**Comment by pczarn** [comment] 2017-02-08 12:36
The config is like for any other loader
For me, the errors come from sass-loader
```
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./app/frontend/App.vue
Module build failed: 
  div.app
^
      @import directive requires a url or quoted path
      in /home/piotr/src/app/frontend/App.vue (line 2, column 1)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./app/frontend/App.vue 4:14-250 13:2-17:4 14:20-256
```
```
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=_v-644c9212&scoped=true!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./app/frontend/containers/Navigation/index.vue
Module build failed: 
div(
^
      @import directive requires a url or quoted path
      in /home/piotr/src/app/frontend/containers/Navigation/index.vue (line 2, column 1)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=_v-644c9212&scoped=true!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./app/frontend/containers/Navigation/index.vue 4:14-303 13:2-17:4 14:20-309
```

**Comment by lanlin** [comment] 2017-02-09 08:38
Hi @amireh , 
I got some similar problems in my project.

![image](https://cloud.githubusercontent.com/assets/3468024/22774811/c13174b0-eee3-11e6-8791-678d68d9cd9c.png)

I build my project with [https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli
) 
and init it with this the webpack template.

**vue init webpack  my_project**   

and after build, i config the module as blow

```javascript
    module: {
    preLoaders: [
      {
        test: /\.vue$/,
        loader: 'happypack/loader?id=eslint-vue',
        include: sourcePaths,
        exclude: [/ext_lib/, /node_modules/],
      },
      {
        test: /\.js$/,
        loader: 'happypack/loader?id=eslint-js',
        include: sourcePaths,
        exclude: [/ext_lib/, /node_modules/]
      }
    ],
    loaders: [
      {
        test: /\.vue$/,
        loader: 'happypack/loader?id=vue'
      },
      {
        test: /\.js$/,
        loader: 'happypack/loader?id=babel',
        include: sourcePaths,
        exclude: [/node_modules/],
      },
      {
        test: /\.json$/,
        loader: 'happypack/loader?id=json',
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'happypack/loader?id=url',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'happypack/loader?id=url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
```

and the plugins

```javascript
   new HappyPack({
      id: 'eslint-js',
      cache: false,
      verbose: true,
      loaders: ['eslint'],
      threadPool: happyThreadPool
    }),
    new HappyPack({
      id: 'eslint-vue',
      cache: false,
      verbose: true,
      loaders: ['eslint'],
      threadPool: happyThreadPool
    }),
    new HappyPack({
      id: 'vue',
      cache: true,
      verbose: true,
      loaders: ['vue'],
      threadPool: happyThreadPool
    }),
    new HappyPack({
      id: 'babel',
      cache: true,
      verbose: true,
      loaders: ['babel'],
      threadPool: happyThreadPool
    }),
    new HappyPack({
      id: 'json',
      cache: true,
      verbose: true,
      loaders: ['json'],
      threadPool: happyThreadPool
    }),
    new HappyPack({
      id: 'url',
      cache: true,
      verbose: true,
      loaders: ['url'],
      threadPool: happyThreadPool
    }),
```

Would you please make a support to the vue-loader?

**Comment by amireh** [comment] 2017-02-09 17:16
So I took a quick look and it seems that that error is caused by vue-loader depending on `this._compiler.context` which wasn't being populated by happypack. I've pushed a change to master to expose that variable so if you can try that out and confirm, we can publish a release.

**Comment by lanlin** [comment] 2017-02-10 02:52
Thanks @amireh ! 
I've tried your new commit, other new errors here

![image](https://cloud.githubusercontent.com/assets/3468024/22812227/805e4c06-ef7e-11e6-93f7-5813b7aab530.png)

```
Module build failed: TypeError: Cannot read property 'postcss' of undefined
Module build failed: TypeError: Cannot read property 'transformToRequire' of undefined
```

**Comment by amireh** [comment] 2017-02-10 03:48
Sorry, I don't think we can support that since the loader is mutating state and is depending on it later:

```javascript
  var vueOptions = this.options.__vueOptions__
```

Not sure where `__vueOptions__` is being populated but I'll bet it's in the loader somewhere.

Such statements are not valid in happypack's context since the loader will be applied in an arbitrary thread and any mutations it causes will not be carried over.

**Comment by lanlin** [comment] 2017-02-10 09:28
Ok, Thank you anyway.

**Comment by Akryum** [comment] 2017-02-13 22:12
There is a [new vue-loader release](https://github.com/vuejs/vue-loader/releases/tag/v11.0.0) that should help with that.

**Comment by yyx990803** [comment] 2017-02-16 23:17
So after `vue-loader@11.0.0`, things that need to be fixed on `vue-loader`'s side are done. However we still need HappyPack to merge #131 to fix issues with `vue-loader` options.

In addition, directly requiring PostCSS plugins in `vue-loader`'s `postcss` option will not work with HappyPack because HappyPack only supports serializable query/options. This can be solved by using a PostCSS config file instead.

**Closed** 2017-02-17 04:27 UTC
Labels: needs context

**Comment by Akryum** [comment] 2017-02-17 09:14
@yyx990803 How do you use extract plugin for the CSS with happypack if it only accept serializable values?

**Comment by yyx990803** [comment] 2017-02-17 14:05
@Akryum AFAIK extract-text-webpack-plugin only needs serializable options and already works with HappyPack

**Comment by TrungRueta** [comment] 2018-02-02 05:37
new Report. After upgrade vue-loader from v13.* to v14.1.0 it break happypack v4.0.1. 
happypack work fine with vue-loader v13, but not with v14. 
after upgade all linkes to *.vue file broken with error : 
```Module build failed: TypeError: Object.defineProperty called on non-object```
. Sorry my english not good so i only can say about error here.

**Comment by yyx990803** [comment] 2018-02-03 19:34
@TrungRueta can you open an issue in `vue-loader` with a **minimal** setup that can reproduce the error?

**Comment by TrungRueta** [comment] 2018-02-04 04:30
@yyx990803 : hi Evan. I created issue post 
https://github.com/vuejs/vue-loader/issues/1152. Hope it enough information to help detect issue. Thankyou!
