### ISSUE TITLE
Trying to use ts loader in happypack, getting 'loader._compiler.plugin is not a function'

### ISSUE THREAD

**Issue by aleksclark** [amireh/happypack#40] opened 2016-05-03 19:29 UTC
What the title says, basically:

```
let loaders: webpack.Loader[] = [
  // Compile TypeScript
  { test: /\.ts$/, loader: 'happypack/loader?id=tsx', exclude: [ /\.(spec|e2e)\.ts$/ ] },
]

plugins.push(new HappyPack({
  id: 'tsx',
  threadPool: happyThreadPool,
  loaders: ['ts'],
}));
```

**Comment by amireh** [comment] 2016-05-07 07:27
That's because the loader is trying to directly access webpack's compiler to register a plugin, which isn't supported in HappyPack (since webpack's compiler lives in the main process).

These loaders need to be rewritten in a way to not rely webpack's internals. I'm working on ts-loader support in #33 so you can track the progress there.

**Comment by amireh** [comment] 2016-05-07 07:27
Closing as duplicate of #33.

**Closed by amireh** 2016-05-07 07:27 UTC
