### ISSUE TITLE
HMR is not working anymore when using happypack

### ISSUE THREAD

**Issue by delijah** [amireh/happypack#75] opened 2016-08-24 10:49 UTC
If If i launch webpack-dev-server over the command line everything works fine, but if i launch it from a javascript file (gulpfile) using the webpack-dev-server javascript module, HMR doesn't work.

Crucial parts of my config:
```
import webpack from 'webpack';
import WebpackDevServer from 'webpack-dev-server';
import path from 'path';

const webpackDevConfig = {
    entry: {
        app: [ 'react-hot-loader/patch', path.resolve('app/scripts/app.js') ],
    },
    devServer: {
        contentBase: path.resolve('dist'),
        hot: true,
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ],
    // ...
};

webpackDevConfig.entry.app.unshift(
    'webpack-dev-server/client?http://localhost:9000/',
    'webpack/hot/only-dev-server'
);

const compiler = webpack(webpackDevConfig, (err, stats) => {
    if (err) throw err;
});

new WebpackDevServer(compiler,
    webpackDevConfig.devServer
).listen(9000);
```

**Comment by amireh** [comment] 2016-08-28 06:33
I think we'll need more info here to troubleshoot:

1. happypack related webpack config
2. something that shows how gulp is running webpack
3. how HMR is not working

**Comment by delijah** [comment] 2016-08-29 08:06
Thanks for your feedback! So i'll give you more details.

HMR is not working means, when i run the webpack-dev-server (command line `gulp webpack`) and change a .js file, the reload (of the touched modules) in the browser is not triggered. No console log from HMR, nothing. When i am using it without gulp, HMR just works as normal, so i can see HMR working in the browsers console.

webpack.dev.config.js
```
const path = require('path');
const webpack = require('webpack');
const HappyPack = require('happypack');
const happyThreadPool = HappyPack.ThreadPool({ size: 10 });

module.exports = {
    debug: true,
    entry: {
        app: [ 'react-hot-loader/patch', path.resolve('app/scripts/app.js') ],
    },
    output: {
        path: path.resolve('dist'),
        filename: '[name].bundle.js',
        publicPath: '/',
    },
    module: {
        loaders: [{
            test: /\.js$/,
            include: path.resolve('app/scripts'),
            loader: 'happypack/loader?id=js',
        }],
    },
    plugins: [
        new HappyPack({
            id: 'js',
            loaders: [ 'babel' ],
            threadPool: happyThreadPool,
        }),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('development'),
            },
        }),
        new webpack.HotModuleReplacementPlugin(),
        // ...
    ],
    devtool: 'cheap-eval-source-map ',
    devServer: {
        contentBase: path.resolve('dist'),
        hot: true,
    },
};
```

gulpfile.babel.js
```
import gulp from 'gulp';
import gulpUtil from 'gulp-util';
import webpack from 'webpack';
import WebpackDevServer from 'webpack-dev-server';
import webpackDevConfig from './webpack.dev.config';

gulp.task('webpack', cb => {
    // https://webpack.github.io/docs/usage-with-gulp.html

    webpackDevConfig.entry.app.unshift(
        'webpack-dev-server/client?http://localhost:9000/',
        'webpack/hot/only-dev-server'
    );

    const compiler = webpack(webpackDevConfig, (err, stats) => {
        if (err) {
            throw new gulpUtil.PluginError('webpack', err);
        }

        if (stats.compilation.errors.length) {
            gulpUtil.log('webpack', '\n' + stats.toString({ colors: true }));
        }
    });

    new WebpackDevServer(compiler,
        webpackDevConfig.devServer
    ).listen(9000);
});
```

**Comment by devpascoe** [comment] 2016-08-31 04:32
hmm i'm also getting the warning in the browser console "[HMR] The following modules couldn't be hot updated: (Full reload needed)"

plugins
        new HappyPack({
            loaders: [ 'babel?presets[]=latest' ]
        }),

loaders
        {
            test: /\.js?$/,
            exclude: /(node_modules|bower_components)/,
            loader: 'happypack/loader'
            query: { presets: ['react-hmre'] }
        }

**Comment by amireh** [comment] 2016-08-31 08:01
I think you're misplacing that `query`, it should be on happypack's loaders array:

```javascript
plugins: [
  new HappyPack({
    loaders: [ 'babel?presets[]=latest&presets[]=react-hmre' ],
    // OR
    loaders: [
      {
        path: 'babel',
        query: {
          presets: [ 'latest', 'react-hmre' ]
        }
      }
    ]
  }),
]
```

Because in your current config, you're passing that query to the `happypack/loader` loader which I'm sure is not what you mean.

**Comment by devpascoe** [comment] 2016-09-01 00:20
bingo! working for me now, thanks

**Comment by amireh** [comment] 2016-09-09 07:49
@delijah I haven't used gulp before, and I suspect there's something with the way it's invoking webpack. If you can reproduce the issue in a small repository (or fork happypack and add an example after the other examples) I will be happy to take a look.

**Comment by delijah** [comment] 2016-09-16 20:44
@amireh I have broken down my app into a small repository. Awesome if you gonna have a look!

https://github.com/delijah/happypack-n-gulp

**Comment by delijah** [comment] 2016-10-11 16:49
Any news on this?

**Comment by amireh** [comment] 2016-10-11 17:46
I should have time for this tomorrow morning, I'll post the update and hopefully a fix too :)

**Comment by amireh** [comment] 2016-10-12 04:44
It wasn't a happypack issue, more like a misuse of the webpack node API. I explained a little over here: https://github.com/delijah/happypack-n-gulp/pull/1

Closing!

**Closed by amireh** 2016-10-12 04:44 UTC
Labels: needs context

**Comment by delijah** [comment] 2016-10-20 14:15
Thanks for your investigations! Well this is the way it is recommended to use webpack with gulp:
https://webpack.github.io/docs/usage-with-gulp.html

I am a bit concerned if errors will be written to the stdout without the callback?
