### ISSUE TITLE
PostCSS plugins are ignored

### ISSUE THREAD

**Issue by ertrzyiks** [amireh/happypack#84] opened 2016-09-13 11:13 UTC
Hey, I've a problem with `postcss-loader` and have created the smallest repo to reproduce it.

https://github.com/ertrzyiks/happypack-postcss-example

First of all I've found that not all options defined in my config are passed to the loader, so updated `SERIALIZABLE_OPTIONS` array with my key, but it still doesnt work. Looks like PostCSS plugins are ignored, because they are passed as an array of functions and can not be serialized [here](https://github.com/amireh/happypack/blob/master/lib/HappyPlugin.js#L232) in `launchAndConfigureThreads`.

Any clues how to resolve it?

**Comment by amireh** [comment] 2016-09-13 11:51
How about we give you a chance to deserialize custom options in such a way that you can reproduce this list of functions on the background threads?

The API I'm thinking of is something like this:

```javascript
{
  postcss__happy: [
    {
      path: 'autoprefixer',
      options: {
        browsers: ['ie 10']
      }
    }
  ],

  plugins: [
    new HappyPack({
      customOptionSerializer: function(compilerOptions) {
        return { postcss: compilerOptions.postcss__happy };
      },

      customOptionDeserializer: function(rawOptions) {
        return {
          postcss: function() {
            return rawOptions.postcss.map(function(postcssModule) {
              return require(postcssModule.path)(postcssModule.options);
            });
          }
        };
      }
    })
  ]
}
```

This will work with the only condition that `customOptionDeserializer` does not depend on the closure (i.e. it can be serialized using `toString()`). And the reason we use a different option name instead of `postcss` so as to not conflict with the original option in case you're not using happypack for a certain build.

---

Honestly, I know this isn't a pretty solution but it's the best I can think of in terms of solving your use-case and not causing regressions. There are good reasons why we don't try to serialize function options.

It might be worth noting that this could've been solved more reasily on the loader's end since if they were accepting paths to functions and arguments (like `[{ path: 'autoprefixer', options: { browsers: [ 'ie10' ] } }]`)  and then materialize them into a list of functions then we could've serialized `postcss` without any modifications.

If you like the suggested solution or can think of a different approach, let me know.

**Comment by ertrzyiks** [comment] 2016-09-13 12:28
Thanks for the fast reply @amireh 

Your suggestion looks fine and might be enough for most use cases, but it will not help me. I mean, it would increase a complexity of my code to the level I think is not worth implementing. It's good enough to know I did not miss something obvious and it is actually a problem in 3rd party, not my usage.

I was very surprised that there is no way to configure `postcss-loader` or even `postcss` itself using a plain object. Unfortunately fixing it in the loader will be replacing one problem with another, since in the latest version it uses internal `this._compilation` https://github.com/postcss/postcss-loader/blob/master/index.js#L86 and crash when used with happypack. 

In the end, I will try to exclude postcss from parallelization in my case and will try to fix it on the loader side, since it's way easier as you said.

Cheers!

**Comment by ertrzyiks** [comment] 2016-09-14 09:57
Looks like there is a discussion around postcss to support plain object config, see postcss/postcss#813

Meanwhile I will suggest postcss-loader to support one of helper libraries: https://github.com/postcss/postcss/issues/813#issuecomment-229815437

**Comment by ertrzyiks** [comment] 2016-10-31 17:47
Hey @amireh, the latest postcss-loader support alternative configuration options which work with happy pack 🎉 Can we close or do we need an action point before? Like update wiki

**Comment by brandondoran** [comment] 2016-11-07 06:22
Hi @ertrzyiks. I have been trying to get postcss-loader with autoprefixer plugin working with HappyJack but haven't had any luck. I've tried the postcss-loader config option for Webpack 1 here: https://github.com/postcss/postcss-loader/blob/1.1.0/README.md#webpack-1x-config. I've also tried with a postcss.config.js file. Would you mind sharing how you were able to get it to work?

**Comment by ertrzyiks** [comment] 2016-11-07 07:21
@brandondoran I've updated my example repo with the latest postcss-loader and you can see it working: https://github.com/ertrzyiks/happypack-postcss-example

**Comment by amireh** [comment] 2016-11-07 11:06
That's great! I'm glad to hear, and thanks a lot @ertrzyiks for providing an example. I will incorporate it into the repository or perhaps make a Wiki article for it. Which do you think is best?

(Closing since it's resolved.)

**Closed by amireh** 2016-11-07 11:06 UTC

**Comment by ertrzyiks** [comment] 2016-11-07 11:15
@amireh I see you have a lot of examples in the repository, feel free to incorporate my example as well. I would just add a note to the wiki to clear that `postcss-loader` is fully supported since v1.1.0 (master readme does not even mention problematic webpack-1 config approach anymore)

**Comment by amireh** [comment] 2016-11-07 11:17
Yeah, I think we can do a better job at reporting known issues in the docs. Thanks again, I'll look into this.

**Comment by brandondoran** [comment] 2016-11-07 19:43
@ertrzyiks Thanks so much for the example! I've noticed that when I add `ExtractTextPlugin` usage I get the following warning:
```
WARNING in ./~/happypack/loader.js?id=sass!./client/assets/styles/account.scss
this._compilation is not available thus `postcss-loader-before-processing` is not supported
```
However, the css file does seem to build correctly. It looks like you had a commit to postcss-loader to emit the warning instead of crashing. Is it safe to ignore this warning?

Out of curiosity I cloned https://github.com/ertrzyiks/happypack-postcss-example and added `ExtractTextPlugin` and I get the warning there too.

**Comment by ertrzyiks** [comment] 2016-11-07 19:52
Hey @brandondoran I'm glad that you find it useful ) It's totally safe to ignore that warning as long as everything works for you. I've added this warning to avoid crash and leave a hint so in case of any strange problem with postcss-loader and happypack you have at least one thing to check.

**Comment by brandondoran** [comment] 2016-11-07 20:56
Hey @ertrzyiks, awesome, that is what I figured. Thanks again for your help on this!

**Comment by acidicX** [comment] 2017-02-17 13:25
@ertrzyiks I'm also using the ExtractTextPlugin and I'm getting those warnings. It is possible to make them less verbose? Maybe only one warning instead of 200 :wink: (depending on the amount of files in my case)?

**Comment by ertrzyiks** [comment] 2017-02-17 14:08
@acidicX this warning comes from [postcss-loader](https://github.com/postcss/postcss-loader/blob/master/index.js#L128), not ExtractTextPlugin. It is triggered because happypack does not support `this._compilation` property and some loader/plugins are not fully functional. Maybe we could add an option to acknowledge lack of _compilation and explicitly silent this warning...

**Comment by creage** [comment] 2017-02-24 08:58
We definitely need to suppress that warning if result is successful and is correct.

**Comment by ertrzyiks** [comment] 2017-02-28 13:42
@creage @acidicX I've created an issue in the postcss-loader repo, lets see what can be done to mitigate this problem. See postcss/postcss-loader#179

**Comment by creage** [comment] 2017-03-01 16:07
Seems to be fixed with 1.3.3 release of postcss-loader. I've tested it and have no warnings any more.

**Comment by dickeylth** [comment] 2017-05-15 11:17
So I guess the `postcss-loader` row in <https://github.com/amireh/happypack/wiki/Loader-Compatibility-List> could be updated now?

**Comment by gyf30827** [comment] 2020-05-15 08:29
webpack: 4.x
happypack : 5.0.1
还是有这个问题（have this problem）
![image](https://user-images.githubusercontent.com/22958382/82029183-34ffe580-96c9-11ea-9f3d-5a11dc1a2d33.png)
