### ISSUE TITLE
Postcss not working with happy

### ISSUE THREAD

**Issue by ahskaus** [amireh/happypack#109] opened 2016-12-13 16:54 UTC
This is what my loader looks like

```
  {
    test: /\.css$/, exclude: ['/vendors/'],
    loader: ExtractTextPlugin.extract('style-loader', 'css-loader?module&importLoaders=1&localIdentName=[name]--[local]-[hash:base64:5]!postcss-loader')
  }

```
I replace that with happy and it falls apart. I am struggling to figure out where to begin trying to fix this.

**Comment by amireh** [comment] 2016-12-13 17:47
ExtractText may be the issue here. Try passing only the `postfix-loader` and `css-loader` through happypack, but leave ExtractText with `style-loader` and `happyloader`, like this:

```javascript
{
  module: {
    loaders: [
      {
        test: /\.css$/, exclude: ['/vendors/'],
        loader: ExtractTextPlugin.extract('style-loader', 'happypack/loader?id=css')
      }
    ]
  },

  plugins: [
    new HappyPack({
      id: 'css',
      loaders: [
        'css-loader?module&importLoaders=1&localIdentName=[name]--[local]-[hash:base64:5]',
        'postcss-loader'
      ]
    })
  ]
}
```

Let me know if that works for you.

**Comment by ahskaus** [comment] 2016-12-15 19:19
Tried it. Unfortunately it didn't work. I did have to put postcss before css loader. That removed half the issues, but not the rest.

**Comment by amireh** [comment] 2016-12-15 19:24
Can you share some logs and other parts of your config please? The plugins at least

**Comment by Benno007** [comment] 2017-01-04 00:38
Hi @amireh , the latest version of ExtractText only accepts one paramter (an object) now. I have attempted to use this:
```
{
                test: /\.css$/,
                exclude: /node_modules/,
                loader: ExtractTextPlugin.extract({fallbackLoader: 'style-loader', loader: 'happypack/loader?id=ctmCSS'})
            }
```

Combined with this plugin:
```new HappyPack({
            verbose: debugMode,
            debug: debugMode,
            cache: true,
            cacheContext: {
                env: process.env.NODE_ENV
            },
            id: 'ctmCSS',
            threadPool: happyThreadPool,
            loaders: [
                'css-loader?root=.&localIdentName=[hash:base64:5]&modules&importLoaders=1',
                'postcss-loader'
            ]
        }),```

But it did not work :(. We use CSS modules and its basically said there isn't a proper CSS loader. Any thoughts?

```

    ERROR in ./packages/ctm-css-traits/traits/util/breakpoint_width.css
    Module parse failed: C:\Dev\git\ctm_everest\packages\ctm-css-traits\traits\u
til\breakpoint_width.css Unexpected character '@' (8:0)
    You may need an appropriate loader to handle this file type.
    | /* A list of the available breakpoints from largest to smallest, used to c
ascade layout sizes down
    |   @see EVT-341 */
    | @value defined_breakpoint_keys: 'lg,md,sm,xs';
    |
    | /* Breakpoints */
     @ ./~/happypack/loader.js?id=ctmCSS!./packages/ctm-components/components/bu
tton/button.css 3:10-81 21:761-832 21:1101-1172 21:1286-1357 21:1759-1830 21:225
0-2321 25:16-87 26:12-83 27:17-88 28:12-83 29:12-83
```

Package.json dependencies:
```
  "dependencies": {
    "axios": "0.15.3",
    "babel-plugin-transform-runtime": "6.15.0",
    "classnames": "2.2.5",
    "cross-env": "3.1.4",
    "cuid": "1.3.8",
    "deep-equal": "1.0.1",
    "express": "4.14.0",
    "express-subdomain": "1.0.5",
    "express-winston": "2.1.2",
    "immutable": "3.8.1",
    "intl": "1.2.5",
    "isomorphic-fetch": "2.2.1",
    "jsep": "0.3.0",
    "moment": "2.17.1",
    "react": "15.4.1",
    "react-autosuggest": "7.0.1",
    "react-dom": "15.4.1",
    "react-helmet": "3.3.0",
    "react-intl": "2.2.2",
    "react-onclickoutside": "5.8.3",
    "react-redux": "5.0.1",
    "react-router": "3.0.0",
    "redux": "3.6.0",
    "redux-logger": "2.7.4",
    "redux-promise": "0.5.3",
    "redux-responsive": "4.1.1",
    "redux-saga": "0.13.0",
    "redux-thunk": "2.1.0",
    "reselect": "2.5.4",
    "sanitize-html": "1.13.0",
    "tether": "1.4.0",
    "validator": "6.2.0",
    "webpack": "2.2.0-rc.3",
    "winston": "2.3.0",
    "winston-daily-rotate-file": "1.4.0"
  },
  "devDependencies": {
    "babel-core": "6.21.0",
    "babel-eslint": "7.1.1",
    "babel-loader": "6.2.10",
    "babel-plugin-css-modules-transform": "^1.1.0",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-es2015-modules-commonjs-optimized": "^6.16.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.2.11",
    "babel-plugin-transform-react-router-optimize": "^1.0.1",
    "babel-polyfill": "6.20.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-es2015-native-modules": "6.9.4",
    "babel-preset-react": "^6.16.0",
    "babel-preset-react-optimize": "1.0.1",
    "babel-preset-stage-0": "6.16.0",
    "babel-register": "6.18.0",
    "chai": "3.5.0",
    "chunk-manifest-webpack-plugin": "1.0.0",
    "copy-webpack-plugin": "4.0.1",
    "css-loader": "0.26.1",
    "cssnano": "3.9.1",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "ctm-postcss-traits": "0.0.1",
    "enzyme": "2.7.0",
    "esdoc": "0.5.2",
    "esdoc-es7-plugin": "0.0.3",
    "eslint": "3.12.2",
    "eslint-config-airbnb": "13.0.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "6.8.0",
    "file-loader": "0.9.0",
    "happypack": "^3.0.2",
    "ignore-styles": "5.0.1",
    "jsdom": "9.9.1",
    "json-loader": "0.5.4",
    "lerna": "2.0.0-beta.31",
    "mocha": "3.2.0",
    "mock-css-modules": "1.0.0",
    "null-loader": "0.1.1",
    "nyc": "10.0.0",
    "postcss-cssnext": "2.9.0",
    "postcss-discard-empty": "2.1.0",
    "postcss-focus": "1.0.0",
    "postcss-loader": "1.2.1",
    "postcss-modules": "0.5.2",
    "postcss-modules-extract-imports": "1.0.1",
    "postcss-modules-values": "1.2.2",
    "postcss-reporter": "3.0.0",
    "postcss-theme": "1.1.1",
    "react-addons-test-utils": "15.4.1",
    "react-hot-loader": "3.0.0-beta.6",
    "redux-devtools": "3.3.1",
    "redux-devtools-dock-monitor": "1.1.1",
    "redux-devtools-log-monitor": "1.1.1",
    "rimraf": "2.5.4",
    "style-loader": "0.13.1",
    "stylelint": "7.7.1",
    "stylelint-config-standard": "15.0.1",
    "supertest": "2.0.1",
    "url-loader": "0.5.7",
    "webpack-dev-middleware": "1.9.0",
    "webpack-hot-middleware": "2.14.0",
    "webpack-manifest-plugin": "1.1.0",
    "webpack2-externals-plugin": "1.0.0"
  },
  "license": "UNLICENSED"
}
```

**Comment by ocolot** [comment] 2017-01-24 19:31
Same thing here with the config you suggested above @amireh. It seems it happen on every css file import. Note that I do server side rendering and I use the `import` syntax, like `import styles from '../styles/somestyle.cs'`. Could this have something to do with `css-modules-require-hook`?

```
ERROR in ./shared/components/Label.jsx
8:25:49 PM web.1 |  Module not found: Error: Cannot resolve module 'happypack/loaders' in /Users/oliviercolot/dev/hazaway/shared/components
8:25:49 PM web.1 |   @ ./shared/components/Label.jsx 13:13-43
```

**Comment by amireh** [comment] 2017-01-24 20:11
Hmmm, the plural `loaders` is very peculiar. It should be `happypack/loader` not `happypack/loaders`, there's no such module.

Is there any clear way to reproduce this @ocolot ??

**Comment by ocolot** [comment] 2017-01-25 10:02
Yikes! Sorry for that.

I got further thanks to your answer and the example repo https://github.com/ertrzyiks/happypack-postcss-example found in another issue.

Nevertheless, it now seems that the postcss config handling changes when using happypack:

```
10:53:19 AM web.1 |  Child extract-text-webpack-plugin:
10:53:19 AM web.1 |      chunk    {0} extract-text-webpack-plugin-output-filename 6.32 kB [rendered]
10:53:19 AM web.1 |          [0] ./~/happypack/loader.js?id=css!./shared/styles/Home.css 4.82 kB {0} [built] [1 error]
10:53:19 AM web.1 |          [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
10:53:19 AM web.1 |      ERROR in ./shared/styles/Footer.css
10:53:19 AM web.1 |      Module parse failed: /Users/oliviercolot/dev/itinari/shared/styles/Footer.css Unexpected character '@' (1:0)
10:53:19 AM web.1 |      You may need an appropriate loader to handle this file type.
10:53:19 AM web.1 |      SyntaxError: Unexpected character '@' (1:0)
10:53:19 AM web.1 |          at Parser.pp$4.raise (/Users/oliviercolot/dev/itinari/node_modules/acorn/dist/acorn.js:2221:15)
10:53:19 AM web.1 |          at Parser.pp$7.getTokenFromCode (/Users/oliviercolot/dev/itinari/node_modules/acorn/dist/acorn.js:2756:10)
10:53:19 AM web.1 |          at Parser.pp$7.readToken (/Users/oliviercolot/dev/itinari/node_modules/acorn/dist/acorn.js:2477:17)
10:53:19 AM web.1 |          at Parser.pp$7.nextToken (/Users/oliviercolot/dev/itinari/node_modules/acorn/dist/acorn.js:2468:15)
10:53:19 AM web.1 |          at Parser.parse (/Users/oliviercolot/dev/itinari/node_modules/acorn/dist/acorn.js:515:10)
10:53:19 AM web.1 |          at Object.parse (/Users/oliviercolot/dev/itinari/node_modules/acorn/dist/acorn.js:3098:39)
10:53:19 AM web.1 |          at Parser.parse (/Users/oliviercolot/dev/itinari/node_modules/webpack/lib/Parser.js:902:15)
10:53:19 AM web.1 |          at NormalModule.<anonymous> (/Users/oliviercolot/dev/itinari/node_modules/webpack/lib/NormalModule.js:104:16)
10:53:19 AM web.1 |          at NormalModule.onModuleBuild (/Users/oliviercolot/dev/itinari/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
10:53:19 AM web.1 |          at nextLoader (/Users/oliviercolot/dev/itinari/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
10:53:19 AM web.1 |          at /Users/oliviercolot/dev/itinari/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
10:53:19 AM web.1 |          at Storage.finished (/Users/oliviercolot/dev/itinari/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
10:53:19 AM web.1 |          at /Users/oliviercolot/dev/itinari/node_modules/graceful-fs/graceful-fs.js:78:16
10:53:19 AM web.1 |          at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
10:53:19 AM web.1 |       @ ./~/happypack/loader.js?id=css!./shared/styles/Home.css 3:10-37 18:26-53
```

Here is my webpack.config.js:

```javascript
const path = require('path')
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const HappyPack = require('happypack')

HappyPack.SERIALIZABLE_OPTIONS = HappyPack.SERIALIZABLE_OPTIONS.concat(['postcss'])

const config = {
  entry: {
    client: ['babel-polyfill', './client'],
    admin: ['babel-polyfill', './admin'],
  },
  output: {
    path: path.resolve(__dirname, 'dist', 'public', 'assets'),
    filename: '[name].entry.js',
    publicPath: '/assets/',
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.css'],
    modulesDirectories: ['node_modules'],
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loaders: ['happypack/loader?id=js'],
        exclude: /node_modules/,
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract(
          'style-loader',
          'happypack/loader?id=css',
        ),
      },
    ],
  },
}


config.plugins = [
  new webpack.optimize.OccurrenceOrderPlugin(),
  new HappyPack({
    id: 'js',
    loaders: ['babel'],
  }),
  new HappyPack({
    id: 'css',
    loaders: [
      `css-loader?modules&importLoaders=1&localIdentName=${process.env.NODE_ENV === 'production' ? '[hash:base64:7]' : '[name]_[local]__[hash:base64:2]'}`,
      'postcss-loader',
    ],
  }),
  new ExtractTextPlugin('[name].css', { allChunks: true }),
]

...
```

The postcss.config.js:

```javascript
module.exports = {
  plugins: [
    require('postcss-url')(),
    require('postcss-cssnext')(),
    require('postcss-assets')(),
    require('postcss-flexbugs-fixes')(),
    require('precss')(),
    require('postcss-browser-reporter')(),
    require('postcss-reporter')(),
  ],
}
```

And the Footer.css file where the crash happens:

```scss
@import "variables";

.container {
  text-align: center;
  padding-top: calc(2 * $gutter);
  padding-bottom: @padding-top;
  background-color: $darkGray;
}

.dot {
  margin-left: $gutter;
  margin-right: $gutter;
  color: $lightBlueGray;
}

.link {
  color: $lightBlueGray !important;
}
```

I guess the crash comes form the `@import` and would therefore be linked to a change in handling the `precss` build. Do you see something that would explain this change?

**Comment by amireh** [comment] 2017-02-17 11:20
FWIW, I think this is a bug in happypack related to extract-text plugin, postcss may be a red herring here. I don't have a solution yet but I'm looking into it.

**Comment by amireh** [comment] 2017-08-26 21:39
closing since i'm not going near extract-text anywhere again, PRs welcome

**Closed by amireh** 2017-08-26 21:39 UTC
Labels: bug

**Comment by xurweb** [comment] 2017-09-26 12:35
hello, @amireh. i also has @ocolot 's issues . i use happypack like this:
`module.exports = {
    entry: glob_entries('./app/front_end/app/pages/*.js'),
    output: {
        path: path.join(__dirname, './build'),
        publicPath: '/build/',
        filename: 'js/[name]_[chunkhash].js'
    },
    externals: {
        'react': 'React',
        'react-dom': 'ReactDom'
    },
    module: {
			loaders: [
				{
					test: /\.js$/,
					exclude: /node_modules/,
					loader: 'happypack/loader?id=js'
				},
        {
          test: /\.scss$/,
          loader: ExtractTextPlugin.extract('style-loader', 'happypack/loader?id=scss')
        },
				// {
				// 	test: /\.scss$/,
				// 	// loader: "style-loader!css-loader!postcss-loader!sass-loader"
				// 	loader: extractCSS.extract(['css-loader', 'postcss-loader', 'sass-loader'])
				// },
        {
					test: /\.css$/,
					loaders: "style-loader!css-loader!postcss-loader"
				}, {
				test: /\.png$|\.jpg$/,
				loader: "base64-image"
			}]
		},
		resolve: {
			alias: {
				'@components': path.join(__dirname, './app/front_end/app/components'),
				'@root': path.join(__dirname, './app'),
				'@actions': path.join(__dirname, './app/front_end/app/actions'),
				'@reducers': path.join(__dirname, './app/front_end/app/reducers'),
				'@middlewares': path.join(__dirname, './app/middlewares'),
				'@controllers': path.join(__dirname, './app/controllers')
			},
			extensions: ['.js', '.jsx']
		},
		plugins: [
			createHappyPlugin('js',  [{
				loader: 'babel-loader',
				options: { babelrc: true, cacheDirectory: true }
			}]),

			createHappyPlugin('scss',  [
        'css-loader?module&importLoaders=1&localIdentName=[name]--[local]-[hash:base64:5]',
        'postcss-loader',
        'scss-loader'
        ]
			),

		]
};

console error:
`
![image](https://user-images.githubusercontent.com/8328525/30860474-cbc406ca-a2f9-11e7-8c47-7014f3bf1734.png)

do you has  some ideal for this?  thank you~

**Comment by amireh** [comment] 2017-09-26 21:31
@xurweb is that webpack 1? if so try setting `resolve.extensions` to `['', '.js', '.jsx']` and see if that helps?

**Comment by xurweb** [comment] 2017-09-27 02:23
thank you for your response. i has already update webpack to v3.5.5。so, that is not problem。 in my package.json about building project is this
`
    "dependencies": {
    "assets-webpack-plugin": "3.4.0",
    "autoprefixer": "6.4.0",
    "autoprefixer-loader": "3.2.0",
    "babel": "6.5.2",
    "babel-core": "6.14.0",
    "babel-loader": "6.2.4",
    "babel-plugin-transform-async-to-generator": "6.8.0",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-es2015-loose": "7.0.0",
    "babel-preset-react": "6.11.1",
    "babel-preset-stage-0": "6.5.0",
    "babel-register": "6.11.6",
    "baobab": "^2.4.3",
    "base64-image": "0.1.0",
    "base64-image-loader": "1.0.0",
    "compression-webpack-plugin": "0.3.1",
    "css-loader": "^0.28.7",
    "extract-text-webpack-plugin": "3.0.0",
    "happypack": "^4.0.0",
    "less-loader": "^4.0.5",
    "lodash": "^4.17.4",
    "map-json-webpack-plugin": "1.1.0",
    "path": "0.12.7",
    "postcss-loader": "0.9.1",
    "sass-loader": "4.0.0",
    "style-loader": "0.13.1",
    "webpack": "3.5.5",
    "webpack-glob-entries": "1.0.1",
    "webpack-md5-hash": "0.0.5"
  },
`
