### ISSUE TITLE
Error when starting with less-loader and ExtractTextPlugin

### ISSUE THREAD

**Issue by Tom910** [amireh/happypack#66] opened 2016-08-02 08:05 UTC
I'm using the settings that are written in @amireh #14 and get an error

TypeError: loaderContext.loadModule is not a function
    at /node_modules/less-loader/index.js:117:18
    at HappyFakeCompiler.HFCPt._handleResponse (/node_modules/happypack/lib/HappyFakeCompiler.js:58:3)

Webpack@1.13.1, less-loader@2.2.3, happypack@2.1.1, extract-text-webpack-plugin@1.0.1

If I use Webpack 2, I get a completely different problem

/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:30
        throw new Error("Signature changed: context parameter added");
        ^

Error: Signature changed: context parameter added
    at Tapable.resolve (/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:30:9)
    at Object.HappyRPCHandler.execute (/node_modules/happypack/lib/HappyRPCHandler.js:25:37)
    at ChildProcess.acceptMessageFromWorker (/node_modules/happypack/lib/HappyThread.js:49:27)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Webpack@2.1.0-beta.20, less-loader@2.2.3, happypack@2.1.1, extract-text-webpack-plugin@v2.0.0-beta.3/extract-text-webpack-plugin@1.0.1

**Comment by todd-richmond** [comment] 2016-08-06 03:10
I had similar problems and had to disable happypack for loader chains in release builds where I was using the extract text plugin. Dev builds were fine because they didn't extract. This code assumes you are using the "id" based happy feature

''
    const happypack = require('happypack');
    const happyThreadPool = happypack.ThreadPool({size: 4});

    config.module.loaders.forEach((loader) => {
        // happypack does not work w/ extract-text
        if (loader.happy && (loader.loader + loader.loaders).indexOf(
            'extract-text-webpack-plugin') === -1) {
            config.plugins.push(new happypack({
                id: loader.happy.id,
                threadPool: happyThreadPool
            }));
        }
    });

**Comment by amireh** [comment] 2016-08-06 09:07
`TypeError: loaderContext.loadModule is not a function` means that loader is using an API that HappyPack doesn't support. The webpack 2 error regarding signature changing is a happypack bug that should be fixed.

If you guys can set up a small test repo that reproduces this I can take a look.

**Comment by Tom910** [comment] 2016-08-06 21:36
Yes, my case works now. PR Added a new example #69

**Comment by amireh** [comment] 2016-08-06 22:15
Can we close this then?

**Comment by Tom910** [comment] 2016-08-08 08:23
@amireh I have reproduced the bug, with the less there is a problem when we do @import. An example of an error is here - https://github.com/Tom910/happypack

**Comment by amireh** [comment] 2016-08-08 09:40
Thank you, will take a look

**Comment by amireh** [comment] 2016-08-08 12:36
This should be functional now on master (in both webpack 1 and 2). Please try it and confirm, it will be available in the next release.

FWIW, the support for that API didn't exist until this patch so it's not really a regression.

**Comment by Tom910** [comment] 2016-08-08 15:02
Yes it is version works to my project
Happy[jsx]: Loaded 3210 entries
Happy[less]: Loaded 434 entries

**Closed** 2016-08-08 15:11 UTC

**Comment by amireh** [comment] 2016-08-08 15:19
Released in v2.2.0.
