### ISSUE TITLE
ModuleNotFoundError causes build to hang

### ISSUE THREAD

**Issue by owiber** [amireh/happypack#19] opened 2016-04-08 16:55 UTC
If an import/require path is wrong, causing a `ModuleNotFoundError` error, the build hangs and never completes.

You can reproduce this in the single-loader example by changing `a.js` to:

```js
require('./b1');
```

**Comment by amireh** [comment] 2016-04-08 18:08
Hmm, I can only reproduce this using the `--bail` webpack option, are you using it?

It seems that webpack is not emitting the proper signal when a module build fails with the bail option enabled... We'd expect `compilation.plugin('failed-module')` to be applied when a module fails to build, but my initial tests show that this isn't happening when bail is enabled.

**Comment by owiber** [comment] 2016-04-08 18:21
Ah, yes, that's correct, with the `--bail` option.

**Comment by amireh** [comment] 2016-08-06 22:20
Closing this as there's not much happypack can do since it's an upstream issue, here's to hoping it goes away in webpack2 otherwise we can re-visit.

**Closed by amireh** 2016-08-06 22:20 UTC
Labels: bug

**Comment by sontek** [comment] 2017-01-02 00:14
With webpack2 still not being fully released and this an existing 5 month old bug.  Any chance there is a way happypack can handle this?

**Comment by amireh** [comment] 2017-01-03 09:20
The only way I can think of is to hook into node `process`'s `uncaughtException` hook, if that works at all anyway. Personally, I'd rather not do this because I know from experience it will cause other issues that may be more subtle.

That said, we can try it and see if it fixes it and perhaps provide an option to opt-in for that behaviour.

**Comment by sontek** [comment] 2017-01-03 09:21
I was able to solve this by using `webpack-fail-plugin` which exits properly even though `--bail` doesn't

**Comment by amireh** [comment] 2017-01-03 09:22
There ^ that's probably a better way to go. Maybe we can document that. Thanks @sontek
